version: "3.9"

services:
  customer_service:
    build:
      context: ./Service1
    ports:
      - "5000"
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          cpus: "0.50"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
        max_attempts: 3

  inventory_service:
    build:
      context: ./Service2
    ports:
      - "5001"
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          cpus: "0.50"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
        max_attempts: 3

  sales_service:
    build:
      context: ./Service3
    ports:
      - "5003"
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          cpus: "0.50"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
        max_attempts: 3

  reviews_service:
    build:
      context: ./Service4
    ports:
      - "5002"
    deploy:
      mode: replicated
      replicas: 2
      resources:
        limits:
          cpus: "0.50"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 256M
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
        max_attempts: 3
